global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'variant-jersey'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['host.docker.internal:8081']
        labels:
          variant: 'A-jersey'

  - job_name: 'variant-rest-controller'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['host.docker.internal:8082']
        labels:
          variant: 'C-rest-controller'

  - job_name: 'variant-spring-data-rest'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['host.docker.internal:8083']
        labels:
          variant: 'D-spring-data-rest'
