apiVersion: 1

# Pre-provision Prometheus and InfluxDB v2 datasources

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false

  - name: InfluxDB-JMeter
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    jsonData:
      version: Flux
      organization: perf
      defaultBucket: jmeter
      tlsSkipVerify: true
    secureJsonData:
      token: admin-token
    editable: true
